version: '3.8'
services:
  job-board-api:
    container_name: job-board-api
    build: ../
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./playwright_data:/var/lib/playwright_data
    depends_on:
      - job-board-api-postgres
    environment:
      PYTHONUNBUFFERED: 1
      JOB_BOARD_POSTGRES_DATABASE_URL: ${JOB_BOARD_POSTGRES_DATABASE_URL}
    networks:
      - job-board-postgres-network
      - job-board-keycloak-network
  job-board-api-postgres:
    container_name: job-board-api-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${JOB_BOARD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JOB_BOARD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${JOB_BOARD_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql
    restart: always
    networks:
      - job-board-postgres-network
  job-board-keycloak-postgres:
    image: postgres:latest
    container_name: job-board-keycloak-postgres
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB}
    ports:
      - "5435:5432"
    volumes:
      - job_board_keycloak_data:/var/keycloak/data
    restart: always
    networks:
      - job-board-keycloak-network
  job-board-keycloak:
    container_name: job-board-keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_LOG_LEVEL: info
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: ["start-dev"]
    ports:
      - "8081:8080"
    depends_on:
      - job-board-api-postgres
    networks:
      - job-board-keycloak-network
      - job-board-postgres-network
networks:
  job-board-postgres-network:
  job-board-keycloak-network:
volumes:
  pgdata:
  playwright_data:
  job_board_keycloak_data:
